# Generated by Django 2.1.5 on 2019-01-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='TESTNAME', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='modelno',
            field=models.CharField(default='MODELNO', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='WARRANTY', max_length=10),
        ),
        migrations.AlterField(
            model_name='producthierarchy',
            name='category',
            field=models.CharField(default='CATEGORY', max_length=100),
        ),
        migrations.AlterField(
            model_name='producthierarchy',
            name='group',
            field=models.CharField(default='GROUP', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='TEST@GMAIL.COM', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profileextension',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.IntegerField(default=10),
        ),
    ]
