# Generated by Django 2.1.5 on 2019-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_date', models.DateField()),
                ('Campaign_name', models.CharField(default='Campaign Name', max_length=100)),
                ('Requester_name', models.CharField(default='Requester Name', max_length=100)),
                ('Campaign_email', models.CharField(default='Email@lge.com', max_length=100)),
                ('Campaign_end_date', models.DateField()),
                ('Campaign_start_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Campaign',
            },
        ),
    ]
