# Generated by Django 2.1.5 on 2019-01-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Campaign_email',
            new_name='campaign_email',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Campaign_end_date',
            new_name='campaign_end_date',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Campaign_name',
            new_name='campaign_name',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Campaign_start_date',
            new_name='campaign_start_date',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Request_date',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Requester_name',
            new_name='requester_name',
        ),
    ]
