# Generated by Django 2.1.5 on 2019-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_textfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='user',
        ),
        migrations.AddField(
            model_name='textfile',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='query',
            field=models.CharField(max_length=1000),
        ),
    ]
